# -*- coding: utf-8 -*-
# Curated factual data for major championship venues.
# Keyed by directory slug under courses/. Facts drawn from public historical records.

COURSES = {
"augusta-national-golf-club": {
    "json_name": "Augusta National Golf Club",
    "type": "Parkland",
    "established": "1932",
    "architect": "Alister MacKenzie & Bobby Jones",
    "par": "72",
    "yardage": "7,555",
    "record_round": ("63", "Nick Price (1986) & Greg Norman (1996)"),
    "record_72": ("268 (−20)", "Dustin Johnson, 2020"),
    "first_major": "1934",
    "about": [
        "Augusta National Golf Club, founded by Bobby Jones and Clifford Roberts on the site of a former plantation and nursery, is the permanent home of the Masters Tournament. Designed by Alister MacKenzie with Jones, the course opened in 1932 and hosted its first Masters in 1934.",
        "Each hole is named for a plant or shrub, and the back-nine stretch of holes 11, 12 and 13 — “Amen Corner” — has decided more Masters than any other piece of ground in golf. Lightning-fast greens, towering pines and Rae's Creek make Augusta one of the most recognizable and demanding venues in the game.",
    ],
    "moments": [
        ("1935", "The shot heard 'round the world", "Gene Sarazen holed a 4-wood from 235 yards for an albatross 2 on the par-5 15th, erasing a three-shot deficit and forcing a playoff he won the next day — the moment that put the young Masters on the map."),
        ("1986", "Nicklaus at 46", "Jack Nicklaus charged home in 30 on the back nine to win his sixth Masters at age 46, the oldest champion in tournament history."),
        ("1997", "Tiger's coronation", "A 21-year-old Tiger Woods won by a record 12 strokes with a then-record 18-under 270, becoming the youngest Masters champion."),
        ("2019", "The comeback", "Tiger Woods captured his fifth Green Jacket and 15th major, his first in nearly 11 years, in one of the sport's great comeback stories."),
        ("2020", "Johnson rewrites the book", "Dustin Johnson posted 20-under 268 in the November Masters, the lowest 72-hole total in tournament history."),
    ],
    "faqs": [
        ("What is the course record at Augusta National?", "The competitive course record is 63, shared by Nick Price (third round, 1986) and Greg Norman (first round, 1996)."),
        ("What is the lowest 72-hole total in Masters history?", "Dustin Johnson holds the record with 20-under-par 268, set when he won the 2020 Masters. Tiger Woods (1997) and Jordan Spieth (2015) share second at 18-under 270."),
        ("Who designed Augusta National?", "The course was designed by Alister MacKenzie in collaboration with Bobby Jones and opened in 1932. It has been continually refined, most notably by adding length and trees in the 2000s."),
    ],
},
"st-andrews": {
    "json_name": "St Andrews",
    "type": "Links",
    "established": "15th century",
    "architect": "Old Tom Morris (evolved)",
    "par": "72",
    "yardage": "7,305",
    "record_round": ("61", "Ross Fisher, 2017 (Dunhill Links)"),
    "record_72": ("269 (−19)", "Tiger Woods, 2000"),
    "first_major": "1873",
    "about": [
        "The Old Course at St Andrews is golf's most storied ground, the “Home of Golf,” where the game has been played for some six centuries. Owned by the public and managed by the St Andrews Links Trust, it has hosted The Open more times than any other venue.",
        "Its enormous double greens, the Swilcan Bridge, the Road Hole 17th and the Valley of Sin in front of the 18th are among the most famous features in golf. Old Tom Morris shaped much of its modern character in the 19th century.",
    ],
    "moments": [
        ("1970", "Nicklaus throws his putter", "Jack Nicklaus won an 18-hole playoff over Doug Sanders after Sanders missed a short putt on 72 — Nicklaus famously hurled his putter skyward in celebration."),
        ("1984", "Seve's fist pump", "Severiano Ballesteros birdied the 72nd hole to beat Tom Watson, raising both fists in an image that became his trademark."),
        ("2000", "Tiger's flawless week", "Tiger Woods won by eight, posting 19-under 269 without finding a single one of the course's 112 bunkers, completing the career Grand Slam at 24."),
        ("2015", "Zach Johnson's playoff", "Zach Johnson won a three-man playoff over Louis Oosthuizen and Marc Leishman in a weather-delayed championship."),
        ("2022", "The 150th Open", "St Andrews hosted the milestone 150th Open, won by Cameron Smith with a closing 64 — a fitting stage for the championship's anniversary."),
    ],
    "faqs": [
        ("What is the course record at the Old Course?", "Ross Fisher shot 61 in the 2017 Alfred Dunhill Links Championship, the course record. In Open competition the lowest round is 65."),
        ("What is the lowest 72-hole total in an Open at St Andrews?", "Tiger Woods set the standard at 19-under-par 269 when he won the 2000 Open by eight strokes."),
        ("How many Opens has St Andrews hosted?", "The Old Course has staged The Open 30 times, more than any other venue, beginning in 1873."),
    ],
},
"prestwick-golf-club": {
    "json_name": "Prestwick Golf Club",
    "type": "Links",
    "established": "1851",
    "architect": "Old Tom Morris",
    "par": "71",
    "yardage": "6,908",
    "record_round": ("—", ""),
    "record_72": ("—", ""),
    "first_major": "1860",
    "about": [
        "Prestwick Golf Club, laid out by Old Tom Morris in 1851, is the birthplace of The Open Championship. The first Open was played here in 1860 over the club's original 12-hole links, and Prestwick hosted the championship for its first dozen years.",
        "Willie Park Sr. won that inaugural Open, and Old Tom Morris and his son Young Tom Morris dominated the early years on this ground. Prestwick staged the championship 24 times before hosting it for the last time in 1925.",
    ],
    "moments": [
        ("1860", "The first Open", "Willie Park Sr. won the inaugural Open Championship over 36 holes at Prestwick, beating Old Tom Morris by two strokes for the Challenge Belt."),
        ("1868", "Young Tom's arrival", "Young Tom Morris won the first of four straight Opens at 17, the youngest major champion in history."),
        ("1870", "Retiring the Belt", "Young Tom Morris won his third consecutive Open and kept the Challenge Belt outright, prompting the creation of the Claret Jug."),
        ("1925", "The final Open", "Prestwick hosted The Open for the 24th and last time; the unruly crowds of the era led the championship to move to roomier venues."),
    ],
    "faqs": [
        ("Why is Prestwick important?", "Prestwick Golf Club hosted the very first Open Championship in 1860 and is regarded as the birthplace of major championship golf."),
        ("How many Opens did Prestwick host?", "Prestwick staged The Open 24 times between 1860 and 1925, second only to St Andrews among Open venues."),
        ("Who designed Prestwick?", "Old Tom Morris laid out the original links in 1851; the course has since been extended from its first 12-hole configuration."),
    ],
},
"muirfield": {
    "json_name": "Muirfield",
    "type": "Links",
    "established": "1891",
    "architect": "Old Tom Morris; Harry Colt (redesign)",
    "par": "71",
    "yardage": "7,245",
    "record_round": ("63", "Rory McIlroy, 2013"),
    "record_72": ("271 (−13)", "Ernie Els, 2002 / Nick Faldo, 1992 (272)"),
    "first_major": "1892",
    "about": [
        "Muirfield, home of the Honourable Company of Edinburgh Golfers — the world's oldest organized golf club — is widely regarded as the fairest of the Open links. Its clever routing of two concentric loops means the wind is rarely in the same direction for more than a few holes.",
        "Originally laid out by Old Tom Morris in 1891 and refined by Harry Colt, Muirfield has produced a roll of champions that reads like a who's-who of the game: Vardon, Hagen, Cotton, Player, Nicklaus, Trevino, Watson, Faldo and Els.",
    ],
    "moments": [
        ("1966", "Nicklaus completes the Slam", "Jack Nicklaus won his first Open here to complete the career Grand Slam, and later named his own course Muirfield Village in tribute."),
        ("1972", "Trevino's miracle", "Lee Trevino holed an improbable chip on the 71st hole to deny Tony Jacklin and successfully defend his title."),
        ("1987", "Faldo's 18 pars", "Nick Faldo played a flawless final round of 18 straight pars in difficult conditions to win his first major."),
        ("2002", "Els survives", "Ernie Els won a four-man playoff after a Saturday storm wrecked the leaders' rounds, claiming his first Open."),
        ("2013", "McIlroy's 63 & Mickelson's charge", "Rory McIlroy set the course record with a 63, but Phil Mickelson's brilliant closing 66 delivered the Claret Jug."),
    ],
    "faqs": [
        ("What is the course record at Muirfield?", "Rory McIlroy holds the Muirfield course record with a 63 shot during the 2013 Open Championship."),
        ("Who has won The Open at Muirfield?", "Champions include Harry Vardon, Walter Hagen, Henry Cotton, Gary Player, Jack Nicklaus, Lee Trevino, Tom Watson, Nick Faldo, Ernie Els and Phil Mickelson (2013)."),
        ("Why is Muirfield considered fair?", "Its routing in two loops of nine, running clockwise and counter-clockwise, constantly changes the wind direction, and there are few blind shots compared with other links."),
    ],
},
"royal-st-georges": {
    "json_name": "Royal St George's",
    "type": "Links",
    "established": "1887",
    "architect": "Dr. Laidlaw Purves",
    "par": "70",
    "yardage": "7,204",
    "record_round": ("63", "Several (Open rounds)"),
    "record_72": ("265 (−15)", "Collin Morikawa, 2021"),
    "first_major": "1894",
    "about": [
        "Royal St George's in Sandwich, Kent, was the first course in England to host The Open, in 1894. Its rumpled, dune-laced fairways and deep bunkers — including one of the deepest in championship golf at the 4th — make it one of the most natural and unpredictable links on the rota.",
        "The course inspired the fictional St Marks in Ian Fleming's golf match between James Bond and Goldfinger. It has crowned a varied list of champions, from Walter Hagen to surprise winners Ben Curtis and Darren Clarke, to Collin Morikawa's record-setting 2021 victory.",
    ],
    "moments": [
        ("1985", "Lyle ends the drought", "Sandy Lyle became the first British winner of The Open in 16 years."),
        ("1993", "Norman's masterpiece", "Greg Norman closed with a 64 to win at 13-under 267, a round Gene Sarazen called the finest he had ever seen."),
        ("2003", "Curtis from nowhere", "Ben Curtis, ranked 396th and playing his first major, stunned the field to win The Open."),
        ("2011", "Clarke's moment", "Darren Clarke held off Dustin Johnson and Phil Mickelson to win an emotional Open at 42."),
        ("2021", "Morikawa's record", "Collin Morikawa won in just his second Open start, setting the course's 72-hole record at 15-under 265."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Royal St George's?", "Collin Morikawa set the record at 15-under-par 265 when he won the 2021 Open Championship."),
        ("When did Royal St George's first host The Open?", "In 1894 it became the first course outside Scotland to stage The Open Championship."),
        ("Who has won at Royal St George's?", "Champions include Walter Hagen, Henry Cotton, Bobby Locke, Sandy Lyle, Greg Norman, Ben Curtis, Darren Clarke and Collin Morikawa."),
    ],
},
"oakmont-country-club": {
    "json_name": "Oakmont Country Club",
    "type": "Parkland",
    "established": "1903",
    "architect": "Henry C. Fownes",
    "par": "70",
    "yardage": "7,255",
    "record_round": ("63", "Johnny Miller, 1973"),
    "record_72": ("272 (−8)", "Larry Nelson, 1983"),
    "first_major": "1927",
    "about": [
        "Oakmont Country Club, built by Henry Fownes in 1903 outside Pittsburgh, is routinely called the hardest course in America. Its lightning, sloping greens, some 175 bunkers including the famous “Church Pews,” and brutal rough have defended par for over a century.",
        "Oakmont has hosted the U.S. Open a record number of times and produced some of the championship's defining moments — from Jack Nicklaus's first professional win to Johnny Miller's final-round 63 to J.J. Spaun's 2025 triumph in a rain-soaked finish.",
    ],
    "moments": [
        ("1962", "Nicklaus turns pro a champion", "A 22-year-old Jack Nicklaus beat hometown favorite Arnold Palmer in an 18-hole playoff for his first professional victory."),
        ("1973", "Miller's 63", "Johnny Miller shot a final-round 63 — long considered the greatest round in major history — to come from six back and win the U.S. Open."),
        ("2007", "Cabrera holds on", "Ángel Cabrera survived Oakmont at 5-over 285 to edge Tiger Woods and Jim Furyk."),
        ("2016", "Johnson's rules drama", "Dustin Johnson won his first major despite a controversial rules review on the final nine, finishing at 4-under 276."),
        ("2025", "Spaun in the storm", "J.J. Spaun closed with a dramatic birdie on the 72nd hole in heavy rain to win his first major at the 2025 U.S. Open."),
    ],
    "faqs": [
        ("What is the course record at Oakmont?", "Johnny Miller's final-round 63 in the 1973 U.S. Open is the celebrated Oakmont record and one of the most famous rounds ever played."),
        ("Why is Oakmont so difficult?", "Its severely sloping, glassy-fast greens, 175-plus bunkers including the Church Pews, and penal rough make it widely regarded as the toughest test in American golf."),
        ("How often has Oakmont hosted the U.S. Open?", "Oakmont has hosted more U.S. Opens than any other course, most recently in 2025."),
    ],
},
"royal-liverpool": {
    "json_name": "Royal Liverpool",
    "type": "Links",
    "established": "1869",
    "architect": "Robert Chambers & George Morris",
    "par": "72",
    "yardage": "7,312",
    "record_round": ("63", "Open rounds (2014/2023)"),
    "record_72": ("270 (−18)", "Tiger Woods, 2006"),
    "first_major": "1897",
    "about": [
        "Royal Liverpool, known to all as Hoylake, is one of England's oldest links and a cradle of championship and amateur golf. It hosted the first Amateur Championship in 1885 and has staged The Open since 1897.",
        "Flat, exposed and firm, Hoylake demands precise strategy and rewards the patient. Bobby Jones won a leg of his 1930 Grand Slam here, and the modern Opens of Tiger Woods, Rory McIlroy and Brian Harman have added to its legend.",
    ],
    "moments": [
        ("1930", "Jones and the Slam", "Bobby Jones won The Open at Hoylake as part of his 1930 Grand Slam season."),
        ("1967", "Roberto's win", "Roberto De Vicenzo won a popular Open at 44, holding off Jack Nicklaus."),
        ("2006", "Tiger's irons", "Tiger Woods won by two on a sun-baked links, hitting driver just once all week and posting 18-under 270 days after his father's death."),
        ("2014", "Rory in control", "Rory McIlroy led wire-to-wire to win at 17-under 271, the third leg of his career major haul."),
        ("2023", "Harman runs away", "Brian Harman dominated in the rain to win by six strokes."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Royal Liverpool?", "Tiger Woods set the standard at 18-under-par 270 in his 2006 Open victory."),
        ("What is Royal Liverpool also known as?", "It is universally called Hoylake, after the town on the Wirral peninsula where it sits."),
        ("Who has won The Open at Hoylake?", "Champions include Bobby Jones, Walter Hagen, Peter Thomson, Roberto De Vicenzo, Tiger Woods, Rory McIlroy and Brian Harman."),
    ],
},
"royal-lytham-st-annes": {
    "json_name": "Royal Lytham & St Annes",
    "type": "Links",
    "established": "1886",
    "architect": "George Lowe; Herbert Fowler (redesign)",
    "par": "70",
    "yardage": "7,086",
    "record_round": ("63", "Open rounds"),
    "record_72": ("267 (−17)", "Tom Lehman, 1996 (271, −13 record era)"),
    "first_major": "1926",
    "about": [
        "Royal Lytham & St Annes, tucked inland behind the Lancashire dunes and ringed by a railway line, is defined by its 200-plus bunkers — more than any other Open venue. Unusually, it opens with a par 3 and finishes with a brutal closing stretch.",
        "Bobby Jones launched the venue's Open history with his 1926 win, and Seve Ballesteros made Lytham his own with victories in 1979 and 1988, the latter sealed with a closing 65.",
    ],
    "moments": [
        ("1926", "Jones from the sand", "Bobby Jones hit a famous long iron from a sandy lie on the 17th to win the first Open at Lytham; a plaque marks the spot."),
        ("1969", "Jacklin ends the wait", "Tony Jacklin became the first British Open champion in 18 years, igniting a home golf boom."),
        ("1979", "Seve the car-park champion", "Severiano Ballesteros won his first major, famously playing from a car park beside the 16th."),
        ("1996", "Lehman leads", "Tom Lehman became the first American professional to win at Lytham, posting 13-under 271."),
        ("2012", "Els capitalizes", "Ernie Els won his second Open after Adam Scott bogeyed the last four holes."),
    ],
    "faqs": [
        ("How many bunkers does Royal Lytham have?", "Royal Lytham & St Annes has more than 200 bunkers, the most of any course on the Open rota."),
        ("Who is most associated with Royal Lytham?", "Seve Ballesteros, who won two of his three Open titles there (1979 and 1988)."),
        ("What is unusual about the layout?", "Lytham is one of the few championship courses that begins with a par 3, and it sits inland from the sea, bordered by a railway."),
    ],
},
"royal-birkdale": {
    "json_name": "Royal Birkdale",
    "type": "Links",
    "established": "1889",
    "architect": "George Lowe; Hawtree & Taylor (redesign)",
    "par": "70",
    "yardage": "7,156",
    "record_round": ("63", "Open rounds"),
    "record_72": ("268 (−20)", "Jordan Spieth, 2017 (12-under)"),
    "first_major": "1954",
    "about": [
        "Royal Birkdale, set among towering Lancashire dunes near Southport, is one of the most respected and best-conditioned links in the world. Its fairways run flat in the valleys between the dunes, giving players fair lies and a true test of ball-striking.",
        "Birkdale has crowned a remarkable list of champions, from Peter Thomson and Arnold Palmer to Tom Watson, Mark O'Meara, Pádraig Harrington and Jordan Spieth, whose 2017 victory featured one of the great recovery holes in Open history.",
    ],
    "moments": [
        ("1961", "Palmer's umbrella", "Arnold Palmer won in a gale, hitting a famous recovery from rough beside the 16th; a plaque marks the spot."),
        ("1976", "Seve announces himself", "A 19-year-old Severiano Ballesteros tied for second behind Johnny Miller, signaling a new star."),
        ("1991", "Baker-Finch soars", "Ian Baker-Finch shot 29 on the front nine of the final round to win going away."),
        ("2008", "Harrington defends", "Pádraig Harrington won his second straight Open in brutal wind with a closing eagle on 17."),
        ("2017", "Spieth's escape", "Jordan Spieth made bogey from the driving range right of the 13th, then played 5-under over the last five holes to beat Matt Kuchar."),
    ],
    "faqs": [
        ("Who won the 2017 Open at Royal Birkdale?", "Jordan Spieth won at 12-under, capped by a remarkable recovery on the 13th and a closing birdie-eagle-birdie-par run."),
        ("Why is Royal Birkdale respected by players?", "Its flat valley fairways between the dunes give fair bounces, making it widely considered one of the fairest and finest links."),
        ("Who has won The Open at Birkdale?", "Champions include Peter Thomson, Arnold Palmer, Lee Trevino, Tom Watson, Mark O'Meara, Pádraig Harrington and Jordan Spieth."),
    ],
},
"baltusrol-golf-club": {
    "json_name": "Baltusrol Golf Club",
    "type": "Parkland",
    "established": "1895",
    "architect": "A.W. Tillinghast (1922 redesign)",
    "par": "72",
    "yardage": "7,400",
    "record_round": ("63", "U.S. Open rounds"),
    "record_72": ("272 (−8)", "Jack Nicklaus, 1980"),
    "first_major": "1903",
    "about": [
        "Baltusrol Golf Club in Springfield, New Jersey, redesigned by A.W. Tillinghast in 1922, is one of only a handful of courses to host the U.S. Open seven times. Its Lower Course finishes with back-to-back par 5s, a rarity at the highest level.",
        "Jack Nicklaus set U.S. Open scoring records here in both 1967 and 1980, and Baltusrol later turned to the PGA Championship, crowning Phil Mickelson (2005) and Jimmy Walker (2016).",
    ],
    "moments": [
        ("1967", "Nicklaus' record", "Jack Nicklaus won the U.S. Open at 275, then a championship record, with a closing birdie on the 18th."),
        ("1980", "The Golden Bear again", "Nicklaus broke his own mark with 272 (−8), proving at 40 he was still the game's best."),
        ("1993", "Janzen ties the record", "Lee Janzen matched Nicklaus's 272 to win the U.S. Open."),
        ("2005", "Mickelson's PGA", "Phil Mickelson won the PGA Championship with a birdie on the 72nd hole."),
        ("2016", "Walker holds off Day", "Jimmy Walker captured his first major, edging Jason Day at the PGA."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Baltusrol?", "Jack Nicklaus (1980) and Lee Janzen (1993) share the U.S. Open record at 272."),
        ("What is unusual about Baltusrol's Lower Course?", "It finishes with consecutive par 5s at the 17th and 18th, an uncommon closing sequence for a major venue."),
        ("Who designed Baltusrol?", "A.W. Tillinghast redesigned the club into its Upper and Lower courses in 1922."),
    ],
},
"oakland-hills": {
    "json_name": "Oakland Hills",
    "type": "Parkland",
    "established": "1918",
    "architect": "Donald Ross; Robert Trent Jones (1951 redesign)",
    "par": "70",
    "yardage": "7,445",
    "record_round": ("63", "Major rounds"),
    "record_72": ("276 (−4)", "PGA / U.S. Open eras"),
    "first_major": "1924",
    "about": [
        "Oakland Hills Country Club near Detroit, designed by Donald Ross and toughened by Robert Trent Jones for the 1951 U.S. Open, earned the nickname “The Monster” from Ben Hogan himself. Its South Course is one of the sternest par-70 tests in America.",
        "Oakland Hills has hosted six U.S. Opens and three PGA Championships, along with the 2004 Ryder Cup, producing champions from Hogan and Gene Littler to Pádraig Harrington.",
    ],
    "moments": [
        ("1951", "Hogan slays the Monster", "Ben Hogan's final-round 67 prompted his famous line: “I'm glad I brought this course, this monster, to its knees.”"),
        ("1961", "Littler's lone major", "Gene Littler won his only major at the U.S. Open."),
        ("1985", "North's second", "Andy North won his second U.S. Open here."),
        ("1996", "Jones holds firm", "Steve Jones, a Monday qualifier, won the U.S. Open."),
        ("2008", "Harrington's double", "Pádraig Harrington won the PGA weeks after his Open title, his third major in 13 months."),
    ],
    "faqs": [
        ("Why is Oakland Hills called The Monster?", "Ben Hogan coined the nickname after Robert Trent Jones's penal 1951 redesign for the U.S. Open."),
        ("Who designed Oakland Hills?", "Donald Ross laid out the original course in 1918; Robert Trent Jones reworked it dramatically in 1951."),
        ("What majors has Oakland Hills hosted?", "Six U.S. Opens and three PGA Championships, plus the 2004 Ryder Cup."),
    ],
},
"southern-hills": {
    "json_name": "Southern Hills",
    "type": "Parkland",
    "established": "1936",
    "architect": "Perry Maxwell",
    "par": "70",
    "yardage": "7,350",
    "record_round": ("63", "Major rounds"),
    "record_72": ("267 (−13)", "Justin Thomas, 2022 (−5 playoff)"),
    "first_major": "1958",
    "about": [
        "Southern Hills Country Club in Tulsa, Oklahoma, a Perry Maxwell design from 1936, is one of America's premier inland championship tests. Its doglegging fairways framed by trees and small, firm Bermuda greens reward shaping the ball both ways.",
        "Often played in fierce summer heat, Southern Hills has hosted three U.S. Opens and a record-tying number of PGA Championships, including Tiger Woods's heat-baked 2007 win and Justin Thomas's 2022 comeback.",
    ],
    "moments": [
        ("1958", "Tommy Bolt's Open", "Tommy Bolt won the U.S. Open in the Oklahoma heat."),
        ("1977", "Green's grit", "Hubert Green won the U.S. Open despite a death threat received during the final round."),
        ("2001", "Goosen recovers", "Retief Goosen three-putted the 72nd hole but won the U.S. Open in an 18-hole playoff."),
        ("2007", "Tiger in the heat", "Tiger Woods won the PGA Championship in 100-degree heat for his 13th major."),
        ("2022", "Thomas storms back", "Justin Thomas erased a seven-shot deficit and won the PGA in a playoff over Will Zalatoris."),
    ],
    "faqs": [
        ("Who won the 2022 PGA Championship at Southern Hills?", "Justin Thomas, who rallied from seven strokes back and won a three-hole playoff over Will Zalatoris."),
        ("Who designed Southern Hills?", "Perry Maxwell designed the course, which opened in 1936."),
        ("What majors has Southern Hills hosted?", "Three U.S. Opens and multiple PGA Championships, making it one of the most frequent modern major venues."),
    ],
},
"carnoustie": {
    "json_name": "Carnoustie",
    "type": "Links",
    "established": "1842",
    "architect": "Allan Robertson; Old Tom Morris; James Braid",
    "par": "71",
    "yardage": "7,402",
    "record_round": ("64", "Open rounds"),
    "record_72": ("269 (−15)", "Open era"),
    "first_major": "1931",
    "about": [
        "Carnoustie on Scotland's Angus coast is widely regarded as the toughest links in championship golf, earning the nickname “Car-nasty.” Its closing stretch — with the Barry Burn snaking across the 17th and 18th — has decided Opens in dramatic fashion.",
        "Ben Hogan won his only Open here in 1953, and the venue is forever linked to Jean van de Velde's collapse on the 72nd hole in 1999, as well as Pádraig Harrington's and Francesco Molinari's triumphs.",
    ],
    "moments": [
        ("1953", "Hogan's only Open", "Ben Hogan won the Claret Jug in his sole Open appearance, completing a three-major season."),
        ("1968", "Player prevails", "Gary Player won The Open at Carnoustie, holding off Jack Nicklaus."),
        ("1999", "Van de Velde's 18th", "Needing only a double bogey to win, Jean van de Velde made triple and lost a playoff to Paul Lawrie, who had begun the day 10 shots back."),
        ("2007", "Harrington over the burn", "Pádraig Harrington twice found the Barry Burn on 18 but won a playoff over Sergio García for his first major."),
        ("2018", "Molinari's poise", "Francesco Molinari played the weekend bogey-free to become the first Italian major champion."),
    ],
    "faqs": [
        ("Why is Carnoustie called the toughest links?", "Its length, wind, deep bunkers and the Barry Burn guarding the closing holes make it the most demanding course on the Open rota — hence the nickname “Car-nasty.”"),
        ("What happened to Jean van de Velde in 1999?", "Leading by three on the 72nd tee, he made triple-bogey 7 — including a shot into the Barry Burn — and lost a playoff to Paul Lawrie."),
        ("Who won The Open at Carnoustie in 2018?", "Francesco Molinari, the first Italian to win a major championship."),
    ],
},
"winged-foot-golf-club": {
    "json_name": "Winged Foot Golf Club",
    "type": "Parkland",
    "established": "1923",
    "architect": "A.W. Tillinghast",
    "par": "70",
    "yardage": "7,477",
    "record_round": ("63", "Major rounds"),
    "record_72": ("274 (−6)", "Bryson DeChambeau, 2020"),
    "first_major": "1929",
    "about": [
        "Winged Foot Golf Club in Mamaroneck, New York, is A.W. Tillinghast at his most demanding. Its West Course features deep bunkers, severe greens and thick rough that have repeatedly turned the U.S. Open into a test of survival.",
        "The 1974 “Massacre at Winged Foot” was won at 7-over par, and in 2020 Bryson DeChambeau was the only player to finish under par for the championship, overpowering the course in a new era of distance.",
    ],
    "moments": [
        ("1929", "Jones survives", "Bobby Jones holed a 12-foot par putt on the 72nd hole to force a playoff he won for the U.S. Open."),
        ("1974", "The Massacre", "Hale Irwin won the U.S. Open at 7-over 287 as Winged Foot's brutal setup overwhelmed the field."),
        ("1984", "Zoeller's white towel", "Fuzzy Zoeller famously waved a towel in mock surrender at Greg Norman, then beat him in a playoff."),
        ("2006", "Mickelson's 18th", "Phil Mickelson made double bogey on the 72nd hole to hand Geoff Ogilvy the U.S. Open."),
        ("2020", "Bryson overpowers", "Bryson DeChambeau bludgeoned the course to win at 6-under 274, the only player under par."),
    ],
    "faqs": [
        ("What was the 'Massacre at Winged Foot'?", "The 1974 U.S. Open, won by Hale Irwin at 7-over-par 287 thanks to one of the most punishing setups in championship history."),
        ("What is the lowest 72-hole total at Winged Foot?", "Bryson DeChambeau's 6-under 274 in 2020 is the U.S. Open record there — and he was the only player to break par that week."),
        ("Who designed Winged Foot?", "A.W. Tillinghast designed both the East and West courses, which opened in 1923."),
    ],
},
"oak-hill-country-club": {
    "json_name": "Oak Hill Country Club",
    "type": "Parkland",
    "established": "1926",
    "architect": "Donald Ross",
    "par": "70",
    "yardage": "7,394",
    "record_round": ("63", "Jason Dufner, 2013"),
    "record_72": ("268 (−12)", "Major eras"),
    "first_major": "1956",
    "about": [
        "Oak Hill Country Club in Rochester, New York, is a classic Donald Ross design framed by thousands of oak trees planted by a club member known as “Dr. John.” Its East Course is a demanding par 70 that has hosted majors across seven decades.",
        "Oak Hill has staged three U.S. Opens and four PGA Championships, with champions including Lee Trevino, Curtis Strange, Jack Nicklaus, Shaun Micheel, Jason Dufner and Brooks Koepka.",
    ],
    "moments": [
        ("1968", "Trevino arrives", "Lee Trevino won his first major at the U.S. Open, breaking 70 in all four rounds."),
        ("1989", "Strange repeats", "Curtis Strange won back-to-back U.S. Opens, the first to do so since Ben Hogan."),
        ("2003", "Micheel's 7-iron", "Shaun Micheel hit a 7-iron to within inches on the 72nd hole to win the PGA, his only PGA Tour victory."),
        ("2013", "Dufner's 63", "Jason Dufner shot 63 to tie the major championship single-round record, then won the PGA."),
        ("2023", "Koepka's fifth", "Brooks Koepka won the PGA for his fifth major and first since joining LIV Golf."),
    ],
    "faqs": [
        ("Who shot 63 at Oak Hill?", "Jason Dufner shot 63 in the 2013 PGA Championship, matching the then-record for the lowest round in major history, and went on to win."),
        ("Who designed Oak Hill?", "Donald Ross designed the East and West courses, which opened in 1926."),
        ("What majors has Oak Hill hosted?", "Three U.S. Opens and four PGA Championships, most recently the 2023 PGA won by Brooks Koepka."),
    ],
},
"royal-troon": {
    "json_name": "Royal Troon",
    "type": "Links",
    "established": "1878",
    "architect": "Willie Fernie (redesign)",
    "par": "71",
    "yardage": "7,190",
    "record_round": ("63", "Open rounds"),
    "record_72": ("264 (−20)", "Henrik Stenson, 2016"),
    "first_major": "1923",
    "about": [
        "Royal Troon on Scotland's Ayrshire coast is a links of two halves — a downwind front nine followed by a punishing return into the prevailing wind. It is home to the famous “Postage Stamp” 8th, the shortest hole in Open golf at around 123 yards but one of the most treacherous.",
        "Troon's defining moment came in 2016, when Henrik Stenson and Phil Mickelson staged a final-round duel for the ages, Stenson winning with a 63 and an Open scoring record of 264.",
    ],
    "moments": [
        ("1973", "Weiskopf's wire-to-wire", "Tom Weiskopf led from start to finish to win The Open."),
        ("1982", "Watson's fourth", "Tom Watson won his fourth of five Open titles at Troon."),
        ("1989", "Calcavecchia's playoff", "Mark Calcavecchia won the first four-hole aggregate playoff at The Open."),
        ("1997", "Leonard's charge", "Justin Leonard came from five back with a closing 65 to win."),
        ("2016", "Stenson vs. Mickelson", "Henrik Stenson shot 63 to beat Phil Mickelson by three, setting the Open record at 20-under 264."),
    ],
    "faqs": [
        ("What is the Postage Stamp?", "Royal Troon's 8th, the shortest hole in Open championship golf at about 123 yards, ringed by deep bunkers and a fearsome short-iron test."),
        ("What is the lowest 72-hole total at Royal Troon?", "Henrik Stenson's 20-under-par 264 in 2016 is the all-time Open Championship scoring record."),
        ("What was the 2016 duel at Troon?", "Stenson and Phil Mickelson pulled away from the field, trading birdies until Stenson's closing 63 sealed a historic win."),
    ],
},
"inverness-club": {
    "json_name": "Inverness Club",
    "type": "Parkland",
    "established": "1903",
    "architect": "Donald Ross (redesign)",
    "par": "71",
    "yardage": "7,255",
    "record_round": ("63", "Major rounds"),
    "record_72": ("276 (−8)", "Major eras"),
    "first_major": "1920",
    "about": [
        "Inverness Club in Toledo, Ohio, redesigned by Donald Ross, is a strategic parkland course that helped change the game's social history: at the 1920 U.S. Open, professionals were for the first time welcomed into the clubhouse.",
        "Inverness has hosted four U.S. Opens and two PGA Championships, the latter both decided in dramatic late fashion by Bob Tway and Paul Azinger.",
    ],
    "moments": [
        ("1920", "Pros in the clubhouse", "Inverness welcomed professionals into the clubhouse for the first time at a U.S. Open; the pros gave the club a commemorative chiming clock."),
        ("1931", "Marathon finish", "Billy Burke beat George Von Elm in a 72-hole double playoff, the longest in U.S. Open history."),
        ("1979", "Irwin holds on", "Hale Irwin won his second U.S. Open."),
        ("1986", "Tway's bunker shot", "Bob Tway holed out from a greenside bunker on the 72nd hole to beat Greg Norman at the PGA."),
        ("1993", "Azinger's playoff", "Paul Azinger won his only major in a playoff over Greg Norman."),
    ],
    "faqs": [
        ("What makes Inverness historically significant?", "At the 1920 U.S. Open it became the first major venue to admit professional golfers into the clubhouse, a milestone in the sport's social history."),
        ("How did Bob Tway win the 1986 PGA?", "He holed out from a greenside bunker on the 72nd hole to overtake Greg Norman."),
        ("Who designed Inverness?", "Donald Ross redesigned the course in the early 20th century, giving it its enduring strategic character."),
    ],
},
"musselburgh-links": {
    "json_name": "Musselburgh Links",
    "type": "Links",
    "established": "1672",
    "architect": "Historic (evolved)",
    "par": "34 (9 holes)",
    "yardage": "2,966",
    "record_round": ("—", ""),
    "record_72": ("—", ""),
    "first_major": "1874",
    "about": [
        "Musselburgh Links, the Old Golf Course, is recognized by Guinness World Records as the oldest playing golf course in the world, with documented play dating to 1672 and a tradition said to stretch back to Mary, Queen of Scots.",
        "This nine-hole links hosted The Open Championship six times between 1874 and 1889, sharing the rota with Prestwick and St Andrews in the championship's early decades. The standard 4¼-inch hole size is believed to have originated here.",
    ],
    "moments": [
        ("1874", "First Open at Musselburgh", "Mungo Park won the first of the six Opens staged on the links."),
        ("1883", "Bob Ferguson's near miss", "Bob Ferguson lost a playoff to Willie Fernie, missing a fourth straight Open title."),
        ("1889", "The final Open", "Willie Park Jr. won the last Open held at Musselburgh before the championship moved to larger venues."),
    ],
    "faqs": [
        ("Why is Musselburgh famous?", "It is recognized as the oldest playing golf course in the world, with play documented from 1672, and it hosted The Open six times in the 19th century."),
        ("How many holes is Musselburgh Links?", "It is a nine-hole links, the configuration over which its six Open Championships were played."),
        ("What golf standard came from Musselburgh?", "The 4¼-inch diameter of the golf hole is widely credited to a hole-cutter first used at Musselburgh in 1829."),
    ],
},
"shinnecock-hills": {
    "json_name": "Shinnecock Hills",
    "type": "Links",
    "established": "1891",
    "architect": "William Flynn (1931 redesign)",
    "par": "70",
    "yardage": "7,445",
    "record_round": ("63", "U.S. Open rounds"),
    "record_72": ("274 (−6)", "U.S. Open era"),
    "first_major": "1896",
    "about": [
        "Shinnecock Hills in Southampton, New York, is one of the founding clubs of the USGA and the site of the second U.S. Open in 1896. Its rolling, windswept linksland and William Flynn's 1931 redesign make it America's closest cousin to a British links.",
        "Shinnecock's modern U.S. Opens have produced worthy champions — Raymond Floyd, Corey Pavin, Retief Goosen and Brooks Koepka — though its firm, fast setup in 2004 famously pushed the course to the edge of playability.",
    ],
    "moments": [
        ("1896", "Early history", "Shinnecock hosted the second U.S. Open and is one of the five clubs that founded the USGA."),
        ("1986", "Floyd at 43", "Raymond Floyd won the U.S. Open at 43, then among the oldest champions."),
        ("1995", "Pavin's 4-wood", "Corey Pavin struck a superb 4-wood to the 72nd green to win his only major."),
        ("2004", "The 7th green", "Retief Goosen won as the baked-out greens, especially the 7th, made the Sunday setup nearly unplayable."),
        ("2018", "Koepka repeats", "Brooks Koepka won back-to-back U.S. Opens with a steady finish."),
    ],
    "faqs": [
        ("Why is Shinnecock Hills historically important?", "It is one of the five founding clubs of the USGA and hosted the second U.S. Open in 1896."),
        ("What happened at the 2004 U.S. Open?", "Firm, fast conditions — especially the par-3 7th green — became so severe that the USGA had to water greens between groups; Retief Goosen won."),
        ("Who redesigned Shinnecock Hills?", "William Flynn redesigned the course in 1931 into the layout used for its modern U.S. Opens."),
    ],
},
"merion-golf-club": {
    "json_name": "Merion Golf Club",
    "type": "Parkland",
    "established": "1912",
    "architect": "Hugh Wilson",
    "par": "70",
    "yardage": "6,996",
    "record_round": ("63", "Major rounds"),
    "record_72": ("281 (+1)", "Justin Rose, 2013"),
    "first_major": "1934",
    "about": [
        "Merion Golf Club's East Course in Ardmore, Pennsylvania, proves that length is not everything. At under 7,000 yards it remains one of the toughest U.S. Open tests, defended by wicker-basket flagsticks, tight fairways, deep bunkers (“the white faces of Merion”) and a fearsome closing stretch.",
        "Merion is woven through golf history: Bobby Jones completed the Grand Slam here in 1930, Ben Hogan struck his famous 1-iron on the 72nd hole in 1950, and Justin Rose won the 2013 U.S. Open at 1-over par.",
    ],
    "moments": [
        ("1930", "Jones completes the Slam", "Bobby Jones won the U.S. Amateur at Merion to complete the only Grand Slam, all four major titles of his era in one year."),
        ("1950", "Hogan's 1-iron", "Sixteen months after a near-fatal car crash, Ben Hogan hit a 1-iron to the 72nd green and won an 18-hole playoff — immortalized in Hy Peskin's photograph."),
        ("1971", "Trevino over Nicklaus", "Lee Trevino tossed a rubber snake on the tee, then beat Jack Nicklaus in an 18-hole playoff for the U.S. Open."),
        ("1981", "Graham's gem", "David Graham played a near-flawless final round, hitting every fairway but one, to win the U.S. Open."),
        ("2013", "Rose holds on", "Justin Rose won at 1-over 281 as Merion's old bones held up against modern power."),
    ],
    "faqs": [
        ("How can Merion host a U.S. Open at under 7,000 yards?", "Its tight fairways, penal rough, deep bunkers, small greens and demanding finishing holes make it a supreme test despite its modest length — Justin Rose won the 2013 U.S. Open at over par."),
        ("What are the wicker baskets at Merion?", "Instead of flags, Merion's flagsticks are topped with woven wicker baskets, a unique tradition that hides wind direction from players."),
        ("What is Merion's place in history?", "Bobby Jones completed his 1930 Grand Slam there, and Ben Hogan hit his legendary 1-iron on the 18th in 1950."),
    ],
},
"medinah-country-club": {
    "json_name": "Medinah Country Club",
    "type": "Parkland",
    "established": "1925",
    "architect": "Tom Bendelow; Roger Packard (redesign)",
    "par": "72",
    "yardage": "7,657",
    "record_round": ("63", "Major rounds"),
    "record_72": ("271 (−17)", "Major eras"),
    "first_major": "1949",
    "about": [
        "Medinah Country Club's Course No. 3, west of Chicago, is a long, tree-lined parkland test bordered by Lake Kadijah. It has hosted three U.S. Opens, two PGA Championships and the unforgettable 2012 Ryder Cup.",
        "Tiger Woods won two PGA Championships at Medinah, in 1999 and 2006, while Hale Irwin's 1990 U.S. Open playoff win there made him, at 45, the oldest U.S. Open champion of the modern era.",
    ],
    "moments": [
        ("1975", "Graham's playoff", "Lou Graham won the U.S. Open in an 18-hole playoff over John Mahaffey."),
        ("1990", "Irwin at 45", "Hale Irwin holed a 45-foot birdie on the 72nd hole, then won a playoff to become the oldest modern U.S. Open champion."),
        ("1999", "Tiger holds off Sergio", "Tiger Woods won the PGA as a 19-year-old Sergio García chased him down the stretch with a famous shot from behind a tree."),
        ("2006", "Woods again", "Tiger Woods won his second PGA at Medinah."),
        ("2012", "Miracle at Medinah", "Europe rallied from 10–6 down on the final day to win the Ryder Cup in one of the event's greatest comebacks."),
    ],
    "faqs": [
        ("What majors has Medinah hosted?", "Three U.S. Opens (1949, 1975, 1990) and two PGA Championships (1999, 2006), both PGAs won by Tiger Woods."),
        ("What was the 'Miracle at Medinah'?", "The 2012 Ryder Cup, when Europe came from 10–6 behind entering Sunday singles to retain the Cup."),
        ("Who is the oldest modern U.S. Open champion?", "Hale Irwin, who won at Medinah in 1990 at age 45."),
    ],
},
"olympic-club": {
    "json_name": "Olympic Club",
    "type": "Parkland",
    "established": "1924",
    "architect": "Sam Whiting",
    "par": "70",
    "yardage": "7,170",
    "record_round": ("63", "U.S. Open rounds"),
    "record_72": ("281 (+1)", "U.S. Open eras"),
    "first_major": "1955",
    "about": [
        "The Olympic Club's Lake Course in San Francisco is famous for one thing above all: upsets. Tilted fairways that kick balls into the rough, a single fairway bunker, and cypress-lined holes have repeatedly undone the game's biggest names.",
        "Time and again the favorite has fallen at Olympic — Hogan, Palmer, Watson and Mickelson among them — while champions Jack Fleck, Billy Casper, Scott Simpson, Lee Janzen and Webb Simpson seized their chances.",
    ],
    "moments": [
        ("1955", "Fleck stuns Hogan", "Unknown municipal pro Jack Fleck birdied two of the last four holes, then beat Ben Hogan in a playoff in one of sport's greatest upsets."),
        ("1966", "Casper's comeback", "Billy Casper made up seven shots over the final nine on Arnold Palmer and won a playoff."),
        ("1987", "Simpson over Watson", "Scott Simpson held off Tom Watson to win the U.S. Open."),
        ("1998", "Janzen's second", "Lee Janzen rallied past Payne Stewart to win his second U.S. Open."),
        ("2012", "Webb's win", "Webb Simpson came from behind as Jim Furyk and others faltered late."),
    ],
    "faqs": [
        ("Why is the Olympic Club known for upsets?", "Its canted fairways and cypress-framed holes have repeatedly denied favorites like Hogan, Palmer, Watson and Mickelson, while lesser-known players seized the title."),
        ("Who beat Ben Hogan at Olympic?", "Jack Fleck, a little-known club professional, beat Hogan in an 18-hole playoff at the 1955 U.S. Open."),
        ("How many U.S. Opens has Olympic hosted?", "Five, in 1955, 1966, 1987, 1998 and 2012."),
    ],
},
"pebble-beach": {
    "json_name": "Pebble Beach",
    "type": "Coastal / Links-style",
    "established": "1919",
    "architect": "Jack Neville & Douglas Grant",
    "par": "72",
    "yardage": "7,075",
    "record_round": ("62", "Tour rounds"),
    "record_72": ("272 (−12)", "Tiger Woods, 2000"),
    "first_major": "1972",
    "about": [
        "Pebble Beach Golf Links on California's Monterey Peninsula is one of the most beautiful courses in the world, with holes hugging the cliffs above Carmel Bay. Its small, severe greens and the iconic seaside 7th, 8th and 18th make it a supreme test despite modest length.",
        "Pebble has hosted the U.S. Open six times and the 1977 PGA, and its public access and annual AT&T Pro-Am have made it the people's major venue. Tom Watson's 1982 chip-in and Tiger Woods's 15-shot rout in 2000 are among golf's signature moments.",
    ],
    "moments": [
        ("1972", "Nicklaus' flagstick", "Jack Nicklaus's 1-iron struck the flagstick on the par-3 17th, setting up the U.S. Open win."),
        ("1982", "Watson's chip-in", "Tom Watson holed a chip from thick rough on the 71st hole to beat Jack Nicklaus — “I told you I was going to make it.”"),
        ("1992", "Kite in the wind", "Tom Kite won his only major in a fierce final-round gale."),
        ("2000", "Tiger's 15", "Tiger Woods won the U.S. Open by a record 15 strokes at 12-under 272, the largest margin in major history."),
        ("2019", "Woodland's week", "Gary Woodland held off Brooks Koepka for his first major, with a deft chip on the 17th."),
    ],
    "faqs": [
        ("What is the record margin at Pebble Beach?", "Tiger Woods won the 2000 U.S. Open by 15 strokes, the largest winning margin in major championship history, at 12-under 272."),
        ("What is Tom Watson's famous shot?", "His chip-in birdie from greenside rough on the par-3 17th in the 1982 U.S. Open, which propelled him past Jack Nicklaus."),
        ("Can the public play Pebble Beach?", "Yes — Pebble Beach is a public resort course, unusual among major championship venues, and hosts the annual AT&T Pebble Beach Pro-Am."),
    ],
},
"pinehurst-resort": {
    "json_name": "Pinehurst Resort",
    "type": "Sandhills",
    "established": "1907",
    "architect": "Donald Ross",
    "par": "70",
    "yardage": "7,588",
    "record_round": ("63", "U.S. Open rounds"),
    "record_72": ("271 (−9)", "Martin Kaymer, 2014"),
    "first_major": "1936",
    "about": [
        "Pinehurst No. 2 in the North Carolina Sandhills is Donald Ross's masterpiece and the course he refined over much of his life while living alongside it. Its crowned, “turtleback” greens repel anything but a perfect shot, making it a relentless test of recovery and nerve.",
        "Now a designated anchor site for future U.S. Opens, Pinehurst is forever associated with Payne Stewart's 1999 winning putt, Michael Campbell's 2005 upset of Tiger Woods, Martin Kaymer's 2014 wire-to-wire win, and Bryson DeChambeau's 2024 triumph.",
    ],
    "moments": [
        ("1999", "Stewart's putt", "Payne Stewart holed a 15-foot par putt on the 72nd hole to beat Phil Mickelson — his final major before his death later that year."),
        ("2005", "Campbell's upset", "Michael Campbell of New Zealand held off a charging Tiger Woods to win the U.S. Open."),
        ("2014", "Kaymer runs away", "Martin Kaymer led wire-to-wire at 9-under 271; the women's U.S. Open was played on the same course the following week."),
        ("2024", "DeChambeau's bunker shot", "Bryson DeChambeau holed a brilliant bunker shot on the 72nd hole to edge Rory McIlroy."),
    ],
    "faqs": [
        ("What makes Pinehurst No. 2 unique?", "Its crowned 'turtleback' greens shed imperfect approaches, demanding precise iron play and creative short-game recovery — a Donald Ross design philosophy."),
        ("Who designed Pinehurst No. 2?", "Donald Ross, who lived beside the course and refined it for decades; it opened in 1907 and reached its famous form in the 1930s."),
        ("What is the lowest 72-hole total at Pinehurst No. 2?", "Martin Kaymer's 9-under-par 271 in 2014, a wire-to-wire U.S. Open victory."),
    ],
},
"myopia-hunt-club": {
    "json_name": "Myopia Hunt Club",
    "type": "Parkland",
    "established": "1894",
    "architect": "Herbert Leeds",
    "par": "72",
    "yardage": "6,539",
    "record_round": ("—", ""),
    "record_72": ("295 (+11)", "U.S. Open era (Anderson, 1901/1905)"),
    "first_major": "1898",
    "about": [
        "Myopia Hunt Club in South Hamilton, Massachusetts, is one of the great relics of early American championship golf. Designed by Herbert Leeds, it hosted four of the first eleven U.S. Opens between 1898 and 1908, when winning scores hovered well above par.",
        "Its small greens and deep bunkers produced some of the highest winning totals in U.S. Open history — Willie Anderson won twice here on his way to a record four U.S. Open titles.",
    ],
    "moments": [
        ("1898", "First Open at Myopia", "Fred Herd won the U.S. Open over 72 holes, the first played at that distance."),
        ("1901", "Anderson's first", "Willie Anderson won the first of his record four U.S. Opens in a playoff."),
        ("1905", "Anderson again", "Willie Anderson won his fourth U.S. Open, a total still unmatched in number though equaled by later greats."),
        ("1908", "Final Open", "Fred McLeod won the last U.S. Open held at Myopia in a playoff."),
    ],
    "faqs": [
        ("Why is Myopia Hunt Club historically significant?", "It hosted four early U.S. Opens (1898–1908) and is associated with Willie Anderson, the first man to win four U.S. Open titles."),
        ("Why were scores so high at Myopia?", "Its small, well-defended greens and the equipment of the era produced winning totals well above par, among the highest in U.S. Open history."),
        ("Who designed Myopia?", "Herbert Leeds laid out the course in the 1890s, building a stern test that hosted the national championship four times."),
    ],
},
"the-country-club": {
    "json_name": "The Country Club",
    "type": "Parkland",
    "established": "1882",
    "architect": "Willie Campbell; William Flynn (redesign)",
    "par": "70",
    "yardage": "7,310",
    "record_round": ("63", "U.S. Open rounds"),
    "record_72": ("274 (−6)", "Matt Fitzpatrick, 2022"),
    "first_major": "1913",
    "about": [
        "The Country Club in Brookline, Massachusetts, one of the five founding clubs of the USGA, is hallowed ground in American golf. Its rocky outcrops, tree-lined fairways and composite championship routing make for a quirky, demanding test.",
        "Brookline is where amateur Francis Ouimet beat the British titans Vardon and Ray in 1913 to spark golf's American boom, and where the 1999 Ryder Cup produced the raucous “Battle of Brookline.”",
    ],
    "moments": [
        ("1913", "Ouimet's upset", "Twenty-year-old amateur Francis Ouimet, with a 10-year-old caddie, beat Harry Vardon and Ted Ray in a playoff — the result that launched golf's popularity in America."),
        ("1963", "Boros in the wind", "Julius Boros won a three-man playoff for the U.S. Open at 43."),
        ("1988", "Strange over Faldo", "Curtis Strange beat Nick Faldo in an 18-hole playoff, then repeated the next year at Oak Hill."),
        ("1999", "Battle of Brookline", "The U.S. stormed back from 10–6 down on Sunday to win the Ryder Cup amid wild scenes around the 17th green."),
        ("2022", "Fitzpatrick from the sand", "Matt Fitzpatrick hit a superb bunker shot on the 72nd hole to win the U.S. Open at the same venue where he won the 2013 U.S. Amateur."),
    ],
    "faqs": [
        ("Why is The Country Club famous?", "It is a founding USGA club and the site of Francis Ouimet's landmark 1913 U.S. Open upset, which sparked golf's growth in America."),
        ("What was the Battle of Brookline?", "The 1999 Ryder Cup, when the U.S. team rallied from 10–6 down in Sunday singles amid one of the most charged atmospheres in golf."),
        ("Who won the 2022 U.S. Open at Brookline?", "Matt Fitzpatrick, who had also won the 2013 U.S. Amateur on the same course."),
    ],
},
"congressional-country-club": {
    "json_name": "Congressional Country Club",
    "type": "Parkland",
    "established": "1924",
    "architect": "Devereux Emmet; Rees Jones (redesign)",
    "par": "71",
    "yardage": "7,569",
    "record_round": ("63", "Major rounds"),
    "record_72": ("268 (−16)", "Rory McIlroy, 2011"),
    "first_major": "1964",
    "about": [
        "Congressional Country Club in Bethesda, Maryland, just outside Washington, D.C., is a long, demanding parkland course with a famous uphill closing hole playing toward the grand clubhouse. Its Blue Course has hosted three U.S. Opens and a PGA Championship.",
        "Congressional is best remembered for Ken Venturi's heat-stricken 1964 win and Rory McIlroy's record-shattering 2011 U.S. Open performance.",
    ],
    "moments": [
        ("1964", "Venturi's ordeal", "Ken Venturi, near collapse from heat exhaustion during a 36-hole final day, was accompanied by a doctor as he won the U.S. Open."),
        ("1976", "Stockton's PGA", "Dave Stockton won the PGA Championship at Congressional."),
        ("1997", "Els holds on", "Ernie Els won his second U.S. Open, edging Colin Montgomerie and Tom Lehman."),
        ("2011", "McIlroy's record", "Rory McIlroy ran away with his first major at 16-under 268, then a U.S. Open scoring record, by eight strokes."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Congressional?", "Rory McIlroy's 16-under-par 268 in the 2011 U.S. Open, which set the championship scoring record at the time."),
        ("Who won the 1964 U.S. Open at Congressional?", "Ken Venturi, who battled severe heat exhaustion during the 36-hole final day under a doctor's watch."),
        ("What majors has Congressional hosted?", "Three U.S. Opens (1964, 1997, 2011) and the 1976 PGA Championship."),
    ],
},
"atlanta-athletic-club": {
    "json_name": "Atlanta Athletic Club",
    "type": "Parkland",
    "established": "1967",
    "architect": "Robert Trent Jones; Rees Jones (redesign)",
    "par": "70",
    "yardage": "7,600",
    "record_round": ("63", "Major rounds"),
    "record_72": ("265 (−15)", "David Toms, 2001"),
    "first_major": "1976",
    "about": [
        "The Atlanta Athletic Club's Highlands Course in Duluth, Georgia, is a long, water-laced parkland test that succeeded the club's original East Lake home of Bobby Jones. Its closing holes around the lake have produced thrilling major finishes.",
        "The club has hosted a U.S. Open and three PGA Championships, including David Toms's 2001 win sealed by a holed fairway wood, and Keegan Bradley's 2011 playoff victory.",
    ],
    "moments": [
        ("1976", "Pate's 5-iron", "Jerry Pate hit a famous 5-iron over water to the 72nd green to win the U.S. Open in his rookie year."),
        ("1981", "Nelson's first", "Larry Nelson won the PGA Championship for his first major."),
        ("2001", "Toms' ace and lay-up", "David Toms made a hole-in-one with a 5-wood, then laid up and got up-and-down on the 72nd to beat Phil Mickelson with a record 15-under 265."),
        ("2011", "Bradley's debut major", "Keegan Bradley won the PGA in a playoff over Jason Dufner in his first major start."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Atlanta Athletic Club?", "David Toms posted 15-under-par 265 to win the 2001 PGA Championship."),
        ("How is the club connected to Bobby Jones?", "Bobby Jones was a lifelong member; the club moved from its original East Lake course to the Highlands site near Duluth in the 1960s."),
        ("What majors has it hosted?", "The 1976 U.S. Open and the 1981, 2001 and 2011 PGA Championships."),
    ],
},
"turnberry": {
    "json_name": "Turnberry",
    "type": "Links",
    "established": "1906",
    "architect": "Willie Fernie; Mackenzie Ross (rebuild)",
    "par": "70",
    "yardage": "7,489",
    "record_round": ("63", "Open rounds"),
    "record_72": ("268 (−12)", "Tom Watson, 1977"),
    "first_major": "1977",
    "about": [
        "Turnberry's Ailsa Course on Scotland's Ayrshire coast, rebuilt by Mackenzie Ross after wartime use as an airfield, is one of the most scenic links in the world, with holes running along the shore beneath a famous lighthouse and views to the Ailsa Craig.",
        "Turnberry has hosted four Opens, none more famous than the 1977 “Duel in the Sun” between Tom Watson and Jack Nicklaus, when the two pulled far clear of the field over a thrilling weekend.",
    ],
    "moments": [
        ("1977", "Duel in the Sun", "Tom Watson shot 65-65 on the weekend to edge Jack Nicklaus by one, both finishing 10 shots clear of third; Watson's 268 set an Open record."),
        ("1986", "Norman's grind", "Greg Norman won his first major in tough, windy conditions."),
        ("1994", "Price's eagle", "Nick Price holed a long eagle putt on the 71st hole to win the Open."),
        ("2009", "Watson's near-miss", "A 59-year-old Tom Watson came within a missed putt on the 72nd hole of winning, then lost a playoff to Stewart Cink."),
    ],
    "faqs": [
        ("What was the 'Duel in the Sun'?", "The 1977 Open at Turnberry, when Tom Watson and Jack Nicklaus traded brilliant rounds, Watson winning by one with a record 268 as the pair finished 10 shots ahead of everyone else."),
        ("What nearly happened in 2009?", "Tom Watson, at 59, led on the 72nd tee and needed a par to win, but bogeyed and lost a playoff to Stewart Cink — nearly the oldest major champion ever."),
        ("What landmark sits beside the course?", "The Turnberry lighthouse overlooks the Ailsa Course, with views across to the Ailsa Craig and the Isle of Arran."),
    ],
},
"valhalla-golf-club": {
    "json_name": "Valhalla Golf Club",
    "type": "Parkland",
    "established": "1986",
    "architect": "Jack Nicklaus",
    "par": "71",
    "yardage": "7,609",
    "record_round": ("62", "Xander Schauffele, 2024"),
    "record_72": ("263 (−21)", "Xander Schauffele, 2024"),
    "first_major": "1996",
    "about": [
        "Valhalla Golf Club in Louisville, Kentucky, a Jack Nicklaus design opened in 1986, has quickly become one of the PGA Championship's favorite modern venues. Its generous landing areas and reachable par 5s reward aggressive play and produce low scoring and dramatic finishes.",
        "Valhalla staged the 2008 Ryder Cup and four PGA Championships, including Tiger Woods's 2000 playoff classic over Bob May and Xander Schauffele's record-setting 2024 win.",
    ],
    "moments": [
        ("1996", "Brooks' playoff", "Mark Brooks won his only major in a playoff over Kenny Perry at the first PGA held at Valhalla."),
        ("2000", "Tiger vs. May", "Tiger Woods edged Bob May in a thrilling three-hole playoff to complete the 'Tiger Slam' run, his third straight major of 2000."),
        ("2008", "Ryder Cup roar", "The U.S. team won the Ryder Cup at Valhalla, ending a run of European dominance."),
        ("2014", "McIlroy in the dark", "Rory McIlroy won the PGA in fading light, his fourth major by age 25."),
        ("2024", "Schauffele's record", "Xander Schauffele birdied the 72nd hole to win his first major at 21-under 263, the lowest score to par in major championship history."),
    ],
    "faqs": [
        ("What is the lowest 72-hole total at Valhalla?", "Xander Schauffele's 21-under-par 263 in the 2024 PGA Championship, the lowest score in relation to par in major championship history."),
        ("Who designed Valhalla?", "Jack Nicklaus designed the course, which opened in 1986; the PGA of America later owned it for many years."),
        ("What was the 2000 PGA at Valhalla?", "Tiger Woods beat Bob May in a three-hole playoff in one of the great major duels, his third consecutive major that year."),
    ],
},
}
